CREATE TABLE INSTRUMENT.TOP_TYPES (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL
);

CREATE TABLE INSTRUMENT.TOP_PRODUCT (
  id SERIAL PRIMARY KEY,
  type INTEGER REFERENCES INSTRUMENT.TOP_TYPES (id)
);